[theme]
# Light 테마를 기본으로 설정
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
base = "light"

[server]
headless = true
fileWatcherType = "none"
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"
port = 8080